name: Update JSONs
on:
  workflow_dispatch:
  schedule:
    - cron:   '0 * * * *'

jobs:
  scrape-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        
      - name: Set up Dart
        uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Clone QuACS data
        uses: actions/checkout@v3
        with:
          repository: quacs/quacs-data
          path: quacs-data

      - name: Run scraper
        run: |
         mkdir -p ./quatalog-data
         dart courseOfferingsScraper.dart          \
              ./quacs-data/semester_data           \
              ./quatalog-data/terms_offered.json   \
              ./quatalog-data/cross_listings.json  \
              ./quatalog-data/prerequisites.json   \
              ./quatalog-data/corequisites.json    \
              ./quatalog-data/attributes.json
        
      - name: Get date
        id: date
        run: echo "::set-output name=date::$(date)"

      - name: Update JSONs
        uses: test-room-7/action-update-file@v1
        with:
            file-path: quatalog-data/*
            commit-msg: ${{ steps.date.outputs.date }}
            github-token: ${{ secrets.GITHUB_TOKEN }}
            
